ORT_PORTAL_ABOGADOS/Controllers/AbogadosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using ORT_PORTAL_ABOGADOS.Context;
using ORT_PORTAL_ABOGADOS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ORT_PORTAL_ABOGADOS.Controllers
{
    public class AbogadosController : Controller
    {
        private readonly DBContext _context;

        public AbogadosController(DBContext context)
        {
            _context = context;
        }

        // GET: Abogados
        public async Task<IActionResult> Index()
        {
            return View(await _context.Abogados.ToListAsync());
        }

        // GET: Abogados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abogado = await _context.Abogados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (abogado == null)
            {
                return NotFound();
            }

            return View(abogado);
        }

        // GET: Abogados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Abogados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Tomo,Folio,Genero,Dni,Area,Usuario,Password")] Abogado abogado)
        {
            if (ModelState.IsValid)
            {
                bool existe = await YaExiste(abogado.Tomo, abogado.Folio, abogado.Dni, abogado.Usuario);
                
                if (!existe)
                {
                    var esValido = await ValidarAbogado(abogado.Tomo, abogado.Folio, abogado.Dni, (int)abogado.Genero, abogado.Nombre, abogado.Apellido);

                    if (esValido)
                    {
                        _context.Add(abogado);
                        await _context.SaveChangesAsync();
                        HttpContext.Session.SetString("Usuario", abogado.Usuario);
                        TempData["RegistroOK"] = "Su registro fue exitoso y el login se realizó automáticamente.";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["RegisterError"] = "Error al validar abogado, corrobore los datos ingresados.";
                    }
                } else
                {
                    TempData["RegisterError"] = "Error al validar abogado, los datos pertenecen a un profesional ya registrado.";
                }
                
            }
            return View(abogado);
        }

        private async Task<bool> ValidarAbogado(int tomo, int folio, int nroDocumento, int genero, string nombre, string apellido)
        {
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true
            };

            using var client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:7136/");

            var request = new
            {
                tomo = tomo,
                folio = folio,
                nroDocumento = nroDocumento,
                genero = genero,
                nombre = nombre,
                apellido = apellido
            };

            var response = await client.PostAsJsonAsync("ValidarAbogado", request);

            if (!response.IsSuccessStatusCode)
                return false; 

            bool existe = await response.Content.ReadFromJsonAsync<bool>();
            return existe;
        }

        private async Task<bool> YaExiste(int tomo, int folio, int dni, string usuario)
        {
            bool valueResult = false;

            var abogado = await _context.Abogados
                .FirstOrDefaultAsync(a => a.Tomo == tomo ||
                                          a.Folio == folio ||
                                          a.Dni == dni ||
                                          a.Usuario == usuario);

            if (abogado != null)
            {
                valueResult = true;
            }

            return valueResult;
        }

        // GET: Abogados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abogado = await _context.Abogados.FindAsync(id);
            if (abogado == null)
            {
                return NotFound();
            }
            return View(abogado);
        }

        // POST: Abogados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Tomo,Folio,Genero,Dni,Area,Usuario,Password")] Abogado abogado)
        {
            if (id != abogado.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(abogado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbogadoExists(abogado.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(abogado);
        }

        // GET: Abogados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var abogado = await _context.Abogados
                .FirstOrDefaultAsync(m => m.Id == id);
            if (abogado == null)
            {
                return NotFound();
            }

            return View(abogado);
        }

        // POST: Abogados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var abogado = await _context.Abogados.FindAsync(id);
            if (abogado != null)
            {
                _context.Abogados.Remove(abogado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbogadoExists(int id)
        {
            return _context.Abogados.Any(e => e.Id == id);
        }
    }
}

ORT_PORTAL_ABOGADOS/Controllers/ConsultasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ORT_PORTAL_ABOGADOS.Context;
using ORT_PORTAL_ABOGADOS.Models;

namespace ORT_PORTAL_ABOGADOS.Controllers
{
    public class ConsultasController : Controller
    {
        private readonly DBContext _context;
        private readonly AccesoController _acceso;


        public ConsultasController(DBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> ConsultasActivas()
        {
            var usuario = HttpContext.Session.GetString("Usuario");

            if (usuario == null)
                return RedirectToAction("Login", "Acceso");

            var abogado = await _context.Abogados
                .FirstOrDefaultAsync(a => a.Usuario == usuario);

            int idUsuario = abogado?.Id ?? -1;

            ViewBag.IdUsuario = idUsuario;

            var consultasActivasList = await _context.Consultas.ToListAsync();

            return View(consultasActivasList);
        }

        public async Task<IActionResult> SolicitudesPendientes()
        {
            //método del controller para mostrar las solicitudes pendientes
            var solicitudesList = await _context.Consultas.Where(c => c.EstaActiva == false && c.IdAbogado == 0).ToListAsync();
            return View(solicitudesList);
        }
        // GET: Consultas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Consultas.ToListAsync());
        }

        // GET: Consultas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consulta == null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        // GET: Consultas/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Crear()
        {
            return View();
        }
        // POST: Consultas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descripcion,NombreCliente,ApellidoCliente,MailCliente")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                consulta.Precio = 0;
                consulta.EstaActiva = false;
                _context.Add(consulta);
                await _context.SaveChangesAsync();

                TempData["CrearExitoso"] = "true";

                return RedirectToAction(nameof(Crear));
            }
            return View(consulta);
        }

        // GET: Consultas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas.FindAsync(id);
            if (consulta == null)
            {
                return NotFound();
            }
            return View(consulta);
        }

        // POST: Consultas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descripcion,Precio,NombreCliente,ApellidoCliente,MailCliente,EstaActiva")] Consulta consulta)
        {
            if (id != consulta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consulta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsultaExists(consulta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(consulta);
        }

        // GET: Consultas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consulta == null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        // GET: Consultas/Delete/5
        public async Task<IActionResult> FinalizarConsulta(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consulta = await _context.Consultas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (consulta == null)
            {
                return NotFound();
            }

            return View(consulta);
        }

        // POST: Consultas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consulta = await _context.Consultas.FindAsync(id);
            if (consulta != null)
            {
                _context.Consultas.Remove(consulta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("FinalizarConsulta")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FinalizConf(int id)
        {
            var consulta = await _context.Consultas.FindAsync(id);
            if (consulta != null)
            {
                _context.Consultas.Remove(consulta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ConsultasActivas));
        }

        private bool ConsultaExists(int id)
        {
            return _context.Consultas.Any(e => e.Id == id);
        }

        public async Task<IActionResult> AceptarSolicitud(int id, double precio)
        {
            var consulta = await _context.Consultas.FindAsync(id);
            if (consulta == null)
                return NotFound();
            var usuario = HttpContext.Session.GetString("Usuario");
            var abogado = await _context.Abogados.FirstOrDefaultAsync(a => a.Usuario == usuario);
            consulta.IdAbogado = abogado.Id;
            consulta.SetPrecio(precio);
            consulta.CambiarEstado();
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(SolicitudesPendientes));
        }
    }
}

ORT_PORTAL_ABOGADOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ORT_PORTAL_ABOGADOS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ORT_PORTAL_ABOGADOS.styles.css" asp-append-version="true" />
</head>

@{
        var usuario = Context.Session.GetString("Usuario");
}

<body style="background-image: url('@Url.Content("~/images/fondo.png")');">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mb-3" id="nav">
            <div class="container-fluid">
                <a><img src="@(Url.Content("~/images/logo.png"))" id="logo" width="80px" alt="Logo"></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Home" asp-action="quienesSomos">Quienes Somos</a>
                        </li>

                        @if (!string.IsNullOrEmpty(usuario))
                        {
                            <li class="nav-item">
                                <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Consultas" asp-action="SolicitudesPendientes">Solicitudes Pendientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Consultas" asp-action="ConsultasActivas">Consultas Activas</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Consultas" asp-action="Crear">Solicitar Consulta</a>
                        </li>
                    </ul>

                    @if (string.IsNullOrEmpty(usuario))
                    {
                        <a class="nav-link" style="color: aliceblue" asp-area="" asp-controller="Abogados" asp-action="Create">Registro de Abogados</a>
                        <p id="iniciarS">Iniciar Sesión -></p>
                    }

                    <img src=@(Url.Content("~/images/Usuario.png")) width="80px" id="iconoUsuario" onclick="mostrarLogin()">
                </div>
            </div>
        </nav>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </header>

    <form id="formularioLogin" method="post" action="/Acceso/Login">
        <p id="tituloForm">Iniciar sesión</p>
        <hr>

        <input type="text" id="usuario" name="usuario" class="campo" placeholder="Mail" required><br>
        <input type="password" id="contrasena" name="password" class="campo" placeholder="Contraseña" required><br><br>
        <div class="mostrar-pass-container">
            <input type="checkbox" id="mostrarPass">
            <label for="mostrarPass">Mostrar contraseña</label>
        </div>
        <br />
        <div style="display: flex; justify-content: space-between">
            <button type="submit" class="login-btn" id="ingresar">Ingresar</button>

            <button class="login-btn">
                <a asp-area="" asp-controller="Abogados" asp-action="Create" style="color:aliceblue">Registrarse</a>
            </button>

            <button type="button" class="login-btn" id="cancelar">Cancelar</button>
        </div>
    </form>


    @if (TempData["CrearExitoso"] != null)
    {
        <script>
            alert('Su consulta se ha creado correctamente.');
            window.location.href = '@Url.Action("Index", "Home")';
        </script>
    }

    @if (TempData["LoginError"] != null)
    {
        <script>
            alert("@TempData["LoginError"]");
        </script>
    }

    @if (TempData["RegistroOK"] != null)
    {
        <script>
            alert("@TempData["RegistroOK"]");
        </script>
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- tu JS (donde está mostrarPass) -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <footer id="Pie">
        <h3>Nuestro contacto</h3>
        <hr style="color: aliceblue;">
        <br><br>

        <div id="contactos">
            <div>
                <img src="@(Url.Content("~/images/telefono.png"))" class="Contacto">
                <p class="contactoTexto"><a href="tel: +5401138595555" class="link">Llamanos</a></p>
            </div>

            <div>
                <img src="@(Url.Content("~/images/mail.png"))" class="Contacto">
                <p class="contactoTexto"><a href="mailto:Estudio.Saraza@gmail.com" class="link">Escribinos</a></p>
            </div>

            <div>
                <img src="@(Url.Content("~/images/whatsapp.png"))" class="Contacto">
                <p class="contactoTexto">
                    <a href="https://wa.me/1138595555" target="_blank" class="link">
                        Chateá con nosotros
                    </a>
                </p>
            </div>
        </div>

        <p id="textoPie">
            © 2025 Equipo 8 | Todos los derechos reservados.
            <a class="link" target="_blank" href="politicas.html">Política de Privacidad</a>
        </p>

        @if (usuario != null)
        {
            <div id="usuarioSesion" style="color:white; padding:10px;">
                Bienvenido, @usuario
                <a href="/Acceso/Logout" style="margin-left:10px; color:yellow;">Cerrar sesión</a>
            </div>

            <script>
                window.usuarioLogueado = true;
            </script>
        }
        else
        {
            <script>
                window.usuarioLogueado = false;
            </script>
        }
    </footer>

</body>
</html>